
name: Release Drafter

on:
  push:
    branches:
      - main
      - 6.x

jobs:
  update_release_draft:
    runs-on: ubuntu-18.04
    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
